// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2SbI_A9HFeCDttrjd5LPxM2tppW_UvcY',
    appId: '1:1090546902511:web:4b62ddf5d40012b39d421a',
    messagingSenderId: '1090546902511',
    projectId: 'ai-app-survey',
    authDomain: 'ai-app-survey.firebaseapp.com',
    storageBucket: 'ai-app-survey.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXk5d1kJiCRrUHPWx_luyUruJ-nbvl58M',
    appId: '1:1090546902511:android:b9a8169f038c97729d421a',
    messagingSenderId: '1090546902511',
    projectId: 'ai-app-survey',
    storageBucket: 'ai-app-survey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ZIiZPb346m5QX7t4TfKZDCzrlkV7KfA',
    appId: '1:1090546902511:ios:8fb7520586585e499d421a',
    messagingSenderId: '1090546902511',
    projectId: 'ai-app-survey',
    storageBucket: 'ai-app-survey.firebasestorage.app',
    iosBundleId: 'com.abthedev.gestureapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ZIiZPb346m5QX7t4TfKZDCzrlkV7KfA',
    appId: '1:1090546902511:ios:8fb7520586585e499d421a',
    messagingSenderId: '1090546902511',
    projectId: 'ai-app-survey',
    storageBucket: 'ai-app-survey.firebasestorage.app',
    iosBundleId: 'com.abthedev.gestureapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2SbI_A9HFeCDttrjd5LPxM2tppW_UvcY',
    appId: '1:1090546902511:web:cff07425b4bd79a39d421a',
    messagingSenderId: '1090546902511',
    projectId: 'ai-app-survey',
    authDomain: 'ai-app-survey.firebaseapp.com',
    storageBucket: 'ai-app-survey.firebasestorage.app',
  );
}
